apiVersion: v1
kind: Service
metadata:
  name: devenv-svc-${USER}
  namespace: machine-learning
spec:
  clusterIP: None
  selector:
    app: devenv
    user: ${USER}
  ports:
    - name: ssh
      port: 22
    - name: ray-gcs
      port: 6379
    - name: ray-dashboard
      port: 8265
    - name: torchrun
      port: 29500
